title: Universal Tool Calling Protocol
description: A modern, flexible, and scalable standard for defining and interacting with tools across various communication protocols.
theme: just-the-docs

# Version information
version: 0.1
versions:
  - name: "0.1"
    url: "/v0.1/"
    branch: "v0.1"
    latest: false
  - name: "latest"
    url: "/"
    branch: "main"
    latest: true

url: https://utcp.io

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/utcp-logo.png"

# Set the path to the favicon
favicon_ico: "site.favicon_ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: black

# Enable callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red

# Enable search
search_enabled: true

# Enable copy code button for code blocks
enable_copy_code_button: true

# Display the table of contents in the sidebar
toc:
  enabled: true

aux_links:
  "UTCP Specification GitHub Repository": "https://github.com/universal-tool-calling-protocol/utcp-specification"

# Footer content
footer_content: "Copyright &copy; 2025 UTCP Contributors. Distributed under the MPL 2.0 License."
